# Generated by Django 5.2.8 on 2025-11-14 19:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artigo",
            name="conteudo",
            field=ckeditor.fields.RichTextField(verbose_name="Conteúdo"),
        ),
        migrations.AlterField(
            model_name="artigo",
            name="resumo",
            field=ckeditor.fields.RichTextField(
                blank=True, config_name="resumo", verbose_name="Resumo"
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="texto",
            field=ckeditor.fields.RichTextField(verbose_name="Texto do Comentário"),
        ),
    ]
