# Generated by Django 5.2.8 on 2025-11-15 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_artigo_conteudo_alter_artigo_resumo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artigo",
            options={"verbose_name": "Artigo", "verbose_name_plural": "Artigos"},
        ),
    ]
