# Generated by Django 5.2.8 on 2025-11-15 20:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_artigo_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, unique=True, verbose_name="Nome"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="artigo",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="artigos", to="blog.tag", verbose_name="Tags"
            ),
        ),
    ]
